SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY, ' ', B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) AS "전체주소", CONCAT(SUBSTRING(B.TLNO, 1, 3), '-', SUBSTRING(B.TLNO, 4, 4), '-', SUBSTRING(B.TLNO, 8, 4)) AS "전화번호" FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID
HAVING COUNT(A.BOARD_ID) >= 3
ORDER BY B.USER_ID DESC

# SELECT USER_ID, NICKNAME, CONCAT(STREET_ADDRESS1, STREET_ADDRESS2) AS "전체주소", CONCAT(SUBSTRING(TLNO, 1, 3), '-', SUBSTRING(TLNO, 4, 4), '-', SUBSTRING(TLNO, 8, 4)) AS "전화번호" FROM USED_GOODS_USER
# WHERE USER_ID IN (SELECT WRITER_ID FROM USED_GOODS_BOARD
#                  GROUP BY WRITER_ID
#                  HAVING COUNT(BOARD_ID) >= 3)
# ORDER BY USER_ID DESC

# SELECT  USER_ID
#         ,NICKNAME
#         ,CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS 전체주소
#         ,CONCAT(SUBSTRING(TLNO,1,3),'-',SUBSTRING(TLNO,4,4),'-',SUBSTRING(TLNO,8,4)) AS 전화번호
#   FROM  USED_GOODS_USER
#  WHERE  USER_ID IN(
#          SELECT  WRITER_ID
#           FROM  USED_GOODS_BOARD
#          GROUP
#             BY  WRITER_ID
#         HAVING  COUNT(BOARD_ID) >= 3)
#  ORDER
#     BY  USER_ID DESC