SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '장기 대여' 
        ELSE '단기 대여' 
    END AS RENT_TYPE
# WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '장기 대여'
#         ELSE '단기 대여' END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC;

# DATE_FORMAT()  > 날짜형식변환
# DATEDIFF(END_DATE, START_DATE)+1 >= 30  > 반납일 - 대여시작일 + 1 = 대여일

 # START_DATE BETWEEN '2022-09-01' AND '2022-09-30'

# SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE,
#        CASE 
#            WHEN START_DATE BETWEEN '2022-09-01' AND '2022-09-30' THEN '장기 대여' 
#            ELSE '단기 대여' 
#        END AS RENT_TYPE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY HISTORY_ID DESC;