SELECT IF(QUARTER(DIFFERENTIATION_DATE) = 1 , "1Q", IF(QUARTER(DIFFERENTIATION_DATE) = 2, "2Q", IF(QUARTER(DIFFERENTIATION_DATE) = 3, "3Q", "4Q"))) AS QUARTER, COUNT(*) AS ECOLI_COUNT FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER