# SELECT ID, NAME, HOST_ID FROM PLACES
# GROUP BY HOST_ID 
# HAVING COUNT(*) > 1
# ORDER BY ID

SELECT ID, NAME, HOST_ID FROM PLACES
WHERE HOST_ID IN (SELECT HOST_ID FROM PLACES
                 GROUP BY HOST_ID
                 HAVING COUNT(HOST_ID)>1)

ORDER BY ID


# SELECT A.ID, A.NAME, A.HOST_ID FROM PLACES AS A
# JOIN (SELECT ID, HOST_ID AS MAX_HOST_ID
#       FROM PLACES
#       GROUP BY HOST_ID 
#       HAVING COUNT(*) > 1
#       ) AS B
#       ON A.ID = B.ID AND A.HOST_ID = B.MAX_HOST_ID
# ORDER BY ID

