SELECT ID, EMAIL, FIRST_NAME, LAST_NAME 
FROM DEVELOPERS 
# WHERE (SKILL_CODE & 1024) = 1024 OR (SKILL_CODE & 256) = 256
WHERE (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) OR (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) 
ORDER BY ID

